export default {
    MARK_NOTIFICATION_AS_READ_BY_ID : 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_NOTIFICATION_AS_READ_BY_All:'MARK_NOTIFICATION_AS_READ_BY_All',
    TOGGLE_NOFICATION_LOADING:'TOGGLE_NOFICATION_LOADING',
    START_MARK_AS_READ:'START_MARK_AS_READ',
    SUCCESS_MARK_AS_READ:'FINISH_MARK_AS_READ',
    GET_ALL_NOTIFICATION:'GET_ALL_NOTIFICATION',
    USER_LOGIN:'USER_LOGIN',
    START_LOGIN:'START_LOGIN',
    SUCCESS_LOGIN:'SUCCESS_LOGIN',
    LOGOUT:'LOGOUT',
    SAVE_AVATAR:'SAVE_AVATAR',
}